import type { ServiceReport } from "@prisma/client";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

type ReportWithRelations = ServiceReport & {
  site: { name: string };
  responses: {
    status: string | null;
    remarks: string | null;
    itemName: string;
    checklistItem: { name: string; order: number } | null;
  }[];
};

export function generateReportPDF(report: ReportWithRelations): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("Prenit Service Inspection Report", 14, 12);
  doc.setFontSize(10);
  doc.text(report.reportNumber, 14, 20);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  let y = 38;

  const details = [
    ["Site", report.site.name],
    ["Path", report.breadcrumb],
    ["Engineer", report.engineerName],
    ["Status", report.status],
    ["Created", new Date(report.createdAt).toLocaleString("en-IN")],
    [
      "Submitted",
      report.submittedAt ? new Date(report.submittedAt).toLocaleString("en-IN") : "-",
    ],
  ];

  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 14, y);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(String(value), pageWidth - 60);
    doc.text(lines, 50, y);
    y += Math.max(6, lines.length * 5);
  });

  y += 4;

  const tableData = report.responses
    .sort((a, b) => (a.checklistItem?.order ?? 0) - (b.checklistItem?.order ?? 0))
    .map((r, i) => [
      String(i + 1),
      r.itemName || r.checklistItem?.name || "-",
      r.status || "-",
      r.remarks || "-",
    ]);

  autoTable(doc, {
    startY: y,
    head: [["#", "Checklist Item", "Status", "Remarks"]],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: [16, 185, 129] },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 62 },
      2: { cellWidth: 22 },
      3: { cellWidth: 88 },
    },
    margin: { left: 14, right: 14 },
  });

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
    .finalY;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by Prenit Service Inspection App", 14, finalY + 10);

  return Buffer.from(doc.output("arraybuffer"));
}
